spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/exemplo
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console